// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;


namespace HugoHelper
{
	public partial class RightClickTableView : NSTableView
	{
		public nint lastClickedRow = -1;

		
		public RightClickTableView (IntPtr handle) : base (handle)
		{
		}


		public override NSMenu MenuForEvent( NSEvent theEvent )
		{
			var point = ConvertPointFromView( theEvent.LocationInWindow, null );
			lastClickedRow = GetRow( point );

			if( lastClickedRow < 0 )
				return null;

			return base.MenuForEvent( theEvent );
		}
	}
}
