// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;


namespace HugoHelper
{
	public partial class ThemePickerViewController : NSViewController
	{
		public ThemePickerViewController( IntPtr handle ) : base( handle )
		{
		}


		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// Create the Table Data Source and populate it
			var dataSource = new ThemePickerDataSource();
			var del = new ThemePickerDelegate( dataSource );

			tableView.DataSource = dataSource;
			tableView.Delegate = del;

			del.onThemeChosen = theme => {
				var winCon = NSApplication.SharedApplication.KeyWindow.WindowController as WindowController;
				winCon.closePopOver();

				AppDelegate.switchTheme( theme );
			};
		}
	}
}
